services:
  # IIPImage主服务
  iipimage:
    image: iipsrv/iipsrv:latest
    container_name: iipimage-server
    ports:
      - "9000:9000"
    volumes:
      - ${IMAGES_PATH:-./images}:/var/www/localhost/images:ro
      - ${LOGS_PATH:-./logs}:/var/log/iipsrv
    environment:
      - VERBOSITY=1
      - LOGFILE=/var/log/iipsrv/iipsrv.log
      - MAX_IMAGE_CACHE_SIZE=${MAX_IMAGE_CACHE_SIZE:-4096mb}
      - JPEG_QUALITY=${JPEG_QUALITY:-90}
      - MAX_CVT=5000
      - MEMCACHED_SERVERS=memcached:11211
      - FILESYSTEM_PREFIX=/var/www/localhost/images/
      - FILESYSTEM_SUFFIX=${IMAGES_SUFFIX:-.tif}
      - BASE_URL=${BASE_URL}
      - CORS=*
    depends_on:
      - memcached
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '16.0'
        reservations:
          cpus: '4.0'
          memory: 4G
    networks:
      - iip-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: iip-nginx
    ports:
      - "${HTTP_PORT:-8081}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - iipimage
    restart: unless-stopped
    networks:
      - iip-network

  # Memcached缓存服务
  memcached:
    image: memcached:alpine
    container_name: iip-memcached
    command: memcached -m 128 -c 1024
    restart: unless-stopped
    networks:
      - iip-network

networks:
  iip-network:
    driver: bridge

volumes:
  iip-images:
  iip-logs: